import React from 'react';
import PropTypes from 'prop-types';

Banner.propTypes = {
      
};

function Banner(props) {
      return (
          <div className="slider-area mb-50 mb-md-30">
                <div id="rev_slider_7_1_wrapper" className="rev_slider_wrapper fullwidthbanner-container" data-alias="homepage-1" data-source="gallery" style={{margin: '0px auto', background: 'transparent', padding: '0px', marginTop: '0px', marginBottom: '0px'}}>
                      {/* START REVOLUTION SLIDER 5.4.7 fullwidth mode */}
                      <div id="rev_slider_7_1" className="rev_slider fullwidthabanner" style={{display: 'none'}} data-version="5.4.7">
                            <ul>
                                  {/* SLIDE  */}
                                  <li data-index="rs-15" data-transition="parallaxtotop,parallaxhorizontal,parallaxtobottom,parallaxvertical,parallaxtoleft,parallaxtoright" data-slotamount="default,default,default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default,default,default" data-easeout="default,default,default,default,default,default" data-masterspeed="default,default,default,default,default,default" data-thumb data-rotate="0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                        {/* MAIN IMAGE */}
                                        <img src="assets/images/revimages/dummy.png" data-bgcolor="#faf7ee" style={{background: '#faf7ee'}} alt="" data-lazyload="assets/images/revimages/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" className="rev-slidebg" data-no-retina />
                                        {/* LAYERS */}
                                        {/* LAYER NR. 1 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-15-layer-17" data-x="['left','center','left','left']" data-hoffset="['1600','-671','-509','-382']" data-y="['middle','middle','top','top']" data-voffset="['330','280','784','367']" data-fontsize="['48','56','72','40']" data-lineheight="['56','64','96','50']" data-fontweight="['400','300','700','700']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1160,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 5, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              1 </div>
                                        {/* LAYER NR. 2 */}
                                        <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-15-layer-21" data-x="['left','left','left','left']" data-hoffset="['1646','1646','1646','1646']" data-y="['top','top','top','top']" data-voffset="['730','730','730','730']" data-width={80} data-height={2} data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:1700,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 6, backgroundColor: 'rgba(0,0,0,0.5)'}}> </div>
                                        {/* LAYER NR. 3 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-15-layer-18" data-x="['left','center','left','left']" data-hoffset="['1750','-607','-327','-263']" data-y="['middle','middle','top','top']" data-voffset="['330','283','795','370']" data-fontsize="['48','34','72','40']" data-lineheight="['56','40','96','50']" data-fontweight="['400','300','700','700']" data-color="['rgb(204,204,204)','rgb(204,204,204)','rgb(51,51,51)','rgb(51,51,51)']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:840,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 7, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#cccccc', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              3 </div>
                                        {/* LAYER NR. 4 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-15-layer-13" data-x="['center','center','left','left']" data-hoffset="['-728','-344','66','41']" data-y="['top','top','top','top']" data-voffset="['321','281','73','76']" data-color="['rgb(51,51,51)','rgb(105,105,105)','rgb(105,105,105)','rgb(105,105,105)']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:700,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 8, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '36px', fontWeight: 600, color: '#333333', letterSpacing: '3px', fontFamily: 'Work Sans'}}>
                                              WOMEN COLLECTION
                                        </div>
                                        {/* LAYER NR. 5 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-15-layer-3" data-x="['center','center','center','left']" data-hoffset="['-584','-200','-69','43']" data-y="['middle','middle','middle','top']" data-voffset="['68','42','-286','133']" data-fontsize="['56','56','56','35']" data-lineheight="['72','72','72','45']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1260,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 9, whiteSpace: 'nowrap', fontSize: '56px', lineHeight: '72px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              Behind the desert <br />
                                              Gifts for girls </div>
                                        {/* LAYER NR. 6 */}
                                        <div className="tp-caption Slider-button-alt rev-btn  tp-resizeme" id="slide-15-layer-20" data-x="['center','center','center','left']" data-hoffset="['-762','-377','-240','45']" data-y="['top','top','top','top']" data-voffset="['589','529','291','248']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;simplelink&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;url&quot;:&quot;\/shop\/&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1610,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(51,51,51);bg:transparent;&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style={{zIndex: 10, whiteSpace: 'nowrap', letterSpacing: '1px', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer'}}>
                                              <a className="revslider-button" href="shop-left-sidebar.html"> SHOP NOW</a> </div>
                                        {/* LAYER NR. 7 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-15-layer-27" data-x="['left','left','left','left']" data-hoffset="['665','237','125','515']" data-y="['top','top','top','top']" data-voffset="['208','244','486','365']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:700,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 11}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['745px','745px','529px','529px']" data-hh="['632px','632px','449px','449px']" data-lazyload="assets/images/revimages/trending/hp1-element-2.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 8 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-15-layer-28" data-x="['left','left','left','left']" data-hoffset="['649','326','41','591']" data-y="['top','top','top','top']" data-voffset="['59','24','402','243']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:970,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 12}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['286px','286px','196px','131px']" data-hh="['292px','292px','200px','134px']" data-lazyload="assets/images/revimages/trending/hp1-element-3.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 9 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-15-layer-29" data-x="['left','left','left','left']" data-hoffset="['1113','563','342','342']" data-y="['top','top','top','top']" data-voffset="['328','342','628','628']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1220,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 13}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['555px','555px','425px','425px']" data-hh="['426px','426px','326px','326px']" data-lazyload="assets/images/revimages/trending/hp1-element-4.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 10 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-15-layer-30" data-x="['left','left','left','left']" data-hoffset="['698','238','3','-23']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','-20','2','-17']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:550,&quot;speed&quot;:2230,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 14}}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['991px','991px','792px','518px']" data-hh="['871px','871px','696px','455px']" data-lazyload="assets/images/revimages/trending/hp1-element-1.png" data-no-retina /> </div>
                                  </li>
                                  {/* SLIDE  */}
                                  <li data-index="rs-16" data-transition="scaledownfromright,scaledownfromleft,scaledownfromtop,scaledownfrombottom,zoomout,zoomin,slotzoom-horizontal,slotzoom-vertical" data-slotamount="default,default,default,default,default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default,default,default,default,default" data-easeout="default,default,default,default,default,default,default,default" data-masterspeed="default,default,default,default,default,default,default,default" data-thumb data-rotate="0,0,0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                        {/* MAIN IMAGE */}
                                        <img src="assets/images/revimages/dummy.png" data-bgcolor="#ebf4f2" style={{background: '#ebf4f2'}} alt="" data-lazyload="assets/images/revimages/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" className="rev-slidebg" data-no-retina />
                                        {/* LAYERS */}
                                        {/* LAYER NR. 11 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-16-layer-17" data-x="['left','center','left','left']" data-hoffset="['1600','-671','-509','-382']" data-y="['middle','middle','top','top']" data-voffset="['330','280','784','367']" data-fontsize="['48','56','72','40']" data-lineheight="['56','64','96','50']" data-fontweight="['400','300','700','700']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1160,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 5, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              2 </div>
                                        {/* LAYER NR. 12 */}
                                        <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-16-layer-21" data-x="['left','left','left','left']" data-hoffset="['1646','1646','1646','1646']" data-y="['top','top','top','top']" data-voffset="['730','730','730','730']" data-width={80} data-height={2} data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:1700,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 6, backgroundColor: 'rgba(0,0,0,0.5)'}}> </div>
                                        {/* LAYER NR. 13 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-16-layer-18" data-x="['left','center','left','left']" data-hoffset="['1750','-607','-327','-263']" data-y="['middle','middle','top','top']" data-voffset="['330','283','795','370']" data-fontsize="['48','34','72','40']" data-lineheight="['56','40','96','50']" data-fontweight="['400','300','700','700']" data-color="['rgb(204,204,204)','rgb(204,204,204)','rgb(51,51,51)','rgb(51,51,51)']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:840,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 7, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#cccccc', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              3 </div>
                                        {/* LAYER NR. 14 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-16-layer-27" data-x="['left','left','center','left']" data-hoffset="['869','1114','0','515']" data-y="['bottom','bottom','bottom','top']" data-voffset="['0','-33','0','365']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:700,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 8}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['799auto','552px','595px','529px']" data-hh="['689','468px','513px','449px']" data-lazyload="assets/images/revimages/trending/hp1-element-6.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 15 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-16-layer-28" data-x="['left','left','left','left']" data-hoffset="['643','1108','381','591']" data-y="['top','top','top','top']" data-voffset="['202','114','530','243']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1070,&quot;speed&quot;:1350,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 9}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['492auto','410px','354px','131px']" data-hh="['359','299px','258px','134px']" data-lazyload="assets/images/revimages/trending/hp1-element-5.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 16 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-16-layer-30" data-x="['left','left','center','center']" data-hoffset="['788','432','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['-5','0','0','0']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:550,&quot;speed&quot;:2230,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 10}}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['822auto','681px','572px','412px']" data-hh="['900','746px','626px','451px']" data-lazyload="assets/images/revimages/trending/hp1-element-7.png" data-no-retina /> </div>
                                        {/* LAYER NR. 17 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-16-layer-13" data-x="['center','center','left','left']" data-hoffset="['-745','-353','66','41']" data-y="['top','top','top','top']" data-voffset="['320','286','73','76']" data-color="['rgb(51,51,51)','rgb(105,105,105)','rgb(105,105,105)','rgb(105,105,105)']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:700,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 11, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '36px', fontWeight: 600, color: '#333333', letterSpacing: '3px', fontFamily: 'Work Sans'}}>
                                              MEN COLLECTION
                                        </div>
                                        {/* LAYER NR. 18 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-16-layer-3" data-x="['center','center','center','left']" data-hoffset="['-598','-200','-80','43']" data-y="['middle','middle','middle','top']" data-voffset="['66','42','-279','133']" data-fontsize="['56','56','56','35']" data-lineheight="['72','72','72','45']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1260,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 12, whiteSpace: 'nowrap', fontSize: '56px', lineHeight: '72px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              Feeling relax day, <br />
                                              enjoy weekend </div>
                                        {/* LAYER NR. 19 */}
                                        <div className="tp-caption Slider-button-alt rev-btn  tp-resizeme" id="slide-16-layer-20" data-x="['center','center','center','left']" data-hoffset="['-762','-364','-246','45']" data-y="['top','top','top','top']" data-voffset="['589','536','305','248']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;simplelink&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;url&quot;:&quot;\/shop\/&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1610,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(51,51,51);bg:transparent;&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style={{zIndex: 13, whiteSpace: 'nowrap', letterSpacing: '1px', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer'}}>
                                              <a className="revslider-button" href="shop-left-sidebar.html"> SHOP NOW</a> </div>
                                  </li>
                                  {/* SLIDE  */}
                                  <li data-index="rs-17" data-transition="slideremoveright,slideremoveleft,slideremoveup,slideremovedown,slideremovehorizontal,slideremovevertical" data-slotamount="default,default,default,default,default,default" data-hideafterloop={0} data-hideslideonmobile="off" data-easein="default,default,default,default,default,default" data-easeout="default,default,default,default,default,default" data-masterspeed="default,default,default,default,default,default" data-thumb data-rotate="0,0,0,0,0,0" data-saveperformance="off" data-title="Slide" data-param1 data-param2 data-param3 data-param4 data-param5 data-param6 data-param7 data-param8 data-param9 data-param10 data-description>
                                        {/* MAIN IMAGE */}
                                        <img src="assets/images/revimages/dummy.png" data-bgcolor="#f4ede7" style={{background: '#f4ede7'}} alt="" data-lazyload="assets/images/revimages/transparent.png" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" className="rev-slidebg" data-no-retina />
                                        {/* LAYERS */}
                                        {/* LAYER NR. 20 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-17-layer-17" data-x="['left','center','left','left']" data-hoffset="['1600','-671','-509','-382']" data-y="['middle','middle','top','top']" data-voffset="['330','280','784','367']" data-fontsize="['48','56','72','40']" data-lineheight="['56','64','96','50']" data-fontweight="['400','300','700','700']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1160,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 5, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              3 </div>
                                        {/* LAYER NR. 21 */}
                                        <div className="tp-caption tp-shape tp-shapewrapper  tp-resizeme" id="slide-17-layer-21" data-x="['left','left','left','left']" data-hoffset="['1646','1646','1646','1646']" data-y="['top','top','top','top']" data-voffset="['730','730','730','730']" data-width={80} data-height={2} data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="shape" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:1700,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 6, backgroundColor: 'rgba(0,0,0,0.5)'}}> </div>
                                        {/* LAYER NR. 22 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-17-layer-18" data-x="['left','center','left','left']" data-hoffset="['1750','-607','-327','-263']" data-y="['middle','middle','top','top']" data-voffset="['330','283','795','370']" data-fontsize="['48','34','72','40']" data-lineheight="['56','40','96','50']" data-fontweight="['400','300','700','700']" data-color="['rgb(204,204,204)','rgb(204,204,204)','rgb(51,51,51)','rgb(51,51,51)']" data-width="none" data-height="none" data-whitespace="nowrap" data-visibility="['on','off','off','off']" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:840,&quot;speed&quot;:1940,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 7, whiteSpace: 'nowrap', fontSize: '48px', lineHeight: '56px', fontWeight: 400, color: '#cccccc', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              3 </div>
                                        {/* LAYER NR. 23 */}
                                        <div className="tp-caption   tp-resizeme rs-parallaxlevel-1" id="slide-17-layer-30" data-x="['left','left','center','center']" data-hoffset="['777','314','17','10']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['43','-143','-30','-68']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="image" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:550,&quot;speed&quot;:1000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 8}}>
                                              <div className="rs-looped rs-slideloop" data-easing data-speed={2} data-xs={0} data-xe={0} data-ys={-10} data-ye={10}><img src="assets/images/revimages/dummy.png" alt="" data-ww="['794px','582px','572px','412px']" data-hh="['664px','638px','626px','451px']" data-lazyload="assets/images/revimages/trending/hp1-element-8.png" data-no-retina /> </div>
                                        </div>
                                        {/* LAYER NR. 24 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-17-layer-13" data-x="['center','center','left','left']" data-hoffset="['-765','-378','66','41']" data-y="['top','top','top','top']" data-voffset="['325','70','73','76']" data-color="['rgb(51,51,51)','rgb(105,105,105)','rgb(105,105,105)','rgb(105,105,105)']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:700,&quot;speed&quot;:1500,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 9, whiteSpace: 'nowrap', fontSize: '16px', lineHeight: '36px', fontWeight: 600, color: '#333333', letterSpacing: '3px', fontFamily: 'Work Sans'}}>
                                              NEW ARRIVALS </div>
                                        {/* LAYER NR. 25 */}
                                        <div className="tp-caption   tp-resizeme" id="slide-17-layer-3" data-x="['center','center','center','left']" data-hoffset="['-598','-218','-80','43']" data-y="['middle','middle','middle','top']" data-voffset="['66','-180','-279','133']" data-fontsize="['56','56','56','35']" data-lineheight="['72','72','72','45']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1260,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style={{zIndex: 10, whiteSpace: 'nowrap', fontSize: '56px', lineHeight: '72px', fontWeight: 400, color: '#333333', letterSpacing: '0px', fontFamily: 'Work Sans'}}>
                                              Shoes collection <br />
                                              ss-2020 </div>
                                        {/* LAYER NR. 26 */}
                                        <div className="tp-caption Slider-button-alt rev-btn  tp-resizeme" id="slide-17-layer-20" data-x="['center','center','center','left']" data-hoffset="['-762','-376','-246','45']" data-y="['top','top','top','top']" data-voffset="['589','316','305','248']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="[{&quot;event&quot;:&quot;click&quot;,&quot;action&quot;:&quot;simplelink&quot;,&quot;target&quot;:&quot;_blank&quot;,&quot;url&quot;:&quot;\/shop\/&quot;,&quot;delay&quot;:&quot;&quot;}]" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1610,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;y:-50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;300&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(51,51,51);bg:transparent;&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[12,12,12,12]" data-paddingright="[35,35,35,35]" data-paddingbottom="[12,12,12,12]" data-paddingleft="[35,35,35,35]" style={{zIndex: 11, whiteSpace: 'nowrap', letterSpacing: '1px', borderColor: 'rgba(0,0,0,1)', outline: 'none', boxShadow: 'none', boxSizing: 'border-box', MozBoxSizing: 'border-box', WebkitBoxSizing: 'border-box', cursor: 'pointer'}}>
                                              <a className="revslider-button" href="shop-left-sidebar.html"> SHOP NOW</a></div>
                                  </li>
                            </ul>
                            <div className="tp-bannertimer tp-bottom" style={{visibility: 'hidden !important'}} />
                      </div>
                </div>{/* END REVOLUTION SLIDER */}
          </div>

      );
}

export default Banner;